###
POST http://localhost:3002/positions HTTP/1.1
Content-Type: application/json

{
    "userID": 1,
    "userPosition":{
        "lat": 56,
        "long": 55
    }
}

######
GET http://localhost/positions?userID=2 HTTP/1.1

