###
GET http://localhost:3001/user?userID=0 HTTP/1.1
Content-Type: application/json
###
POST http://localhost:3001/users HTTP/1.1
Content-Type: application/json

{
    "userIDs": [1,2,3,4]
}
###
GET http://localhost/users?limit=1000 HTTP/1.1

